# build machine
FROM node:14-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./

RUN rm -rf node_modules && yarn install --immutable --silent

COPY . ./

RUN npm run build-prod

RUN ls /app

# production machine
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY productionConfig/nginx.conf /etc/nginx/conf.d/default.conf
RUN ls /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
